--1)How many total admissions were recorded in the hospital?
SELECT COUNT(*) AS total_admissions
FROM hospital_data;

-- 2) How many admissions were recorded for each department?

SELECT
    Department_Name,
    COUNT(*) AS total_admissions
FROM hospital_data
GROUP BY Department_Name
ORDER BY total_admissions DESC;

-- 3) What is the average bill amount for each department?

SELECT
    Department_Name,
    ROUND(AVG(Total_Bill_INR), 2) AS average_bill
FROM hospital_data
GROUP BY Department_Name
ORDER BY average_bill DESC;

-- 4) What is the total billing revenue generated by each department?

SELECT
    Department_Name,
    SUM(Total_Bill_INR) AS total_revenue
FROM hospital_data
GROUP BY Department_Name
ORDER BY total_revenue DESC;


-- 5) What is the average length of stay for hospital patients?

SELECT
    ROUND(AVG(Length_of_Stay_Days), 2) AS average_length_of_stay
FROM hospital_data;


-- 6) What is the total billing amount generated by each insurance type?

SELECT
    Insurance_Type,
    SUM(Total_Bill_INR) AS total_billing
FROM hospital_data
GROUP BY Insurance_Type
ORDER BY total_billing DESC;


-- 7) What is the average bill amount for each treatment type?

SELECT
    Treatment,
    ROUND(AVG(Total_Bill_INR), 2) AS average_bill
FROM hospital_data
GROUP BY Treatment
ORDER BY average_bill DESC;


-- 8) How many admissions were recorded each month?

SELECT
    strftime('%Y-%m', Admission_Date) AS admission_month,
    COUNT(*) AS total_admissions
FROM hospital_data
GROUP BY admission_month
ORDER BY admission_month;


-- 9) What percentage of patients were readmitted within 30 days?

SELECT
    Readmission_30_Days,
    COUNT(*) AS patient_count,
    ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM hospital_data),
        2
    ) AS percentage
FROM hospital_data
GROUP BY Readmission_30_Days;

-- 10) How many admissions had a total bill above INR 100,000?

SELECT
    COUNT(*) AS high_bill_cases
FROM hospital_data
WHERE Total_Bill_INR > 100000;

